[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

# [config.wallpaper]
# command = "swww"
# arguments = ["img", "--transition-type", "center"]
# set = true

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord-background.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.vicinae]
input_path = '~/.config/matugen/templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'

[templates.neovim]
input_path = '~/.config/matugen/templates/neovim/template.lua'
output_path = '~/.config/nvim/generated.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.niri]
input_path = '~/.config/matugen/templates/niri.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.helix]
input_path = '~/.config/matugen/templates/helix.toml'
output_path = '~/.config/helix/themes/matugen.toml'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.zellij]
input_path = '~/.config/matugen/templates/zellij.kdl'
output_path = '~/.config/zellij/themes/colors.kdl'
post_hook = "sed -i 's/theme \"Matugen\"/theme \"default\"/g' ~/.config/zellij/config.kdl && sed -i 's/theme \"default\"/theme \"Matugen\"/g' ~/.config/zellij/config.kdl"

[templates.noctalia]
input_path = '~/.config/matugen/templates/noctalia.json'
output_path = '~/.config/noctalia/colors.json'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop'

[templates.opencode]
input_path = '~/.config/matugen/templates/opencode-colors.json'
output_path = '~/.config/opencode/themes/matugen.json'
